### ISSUE TITLE
Add JSON schema for neo4j2owl_config.json + script to test & GitHub Action to test changes

### ISSUE THREAD

**Issue by dosumis** [OBASKTools/obask#9]
[neo4j2owl_config_schema.json](https://github.com/kharchenkolab/cap-pipeline-config/blob/development/config/prod/neo4j2owl_config_schema.json)

**Comment by ubyndr** [comment]
I moved the script and action we have been using to this repo but it got deleted. I didn't noticed the deletion in this commit; https://github.com/OBASKTools/obask/commit/f6265caaed767422b4427b971af0222144bc7720. Adding schema should solve this issue. I'm gonna test it and make a PR.
